type: google.api.Service
config_version: 3

name: liveq.endpoints.liveq-273521.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: LiveQ gRPC API
apis:
- name: liveq.LiveQ

#
# API usage restrictions.
#
usage:
  rules:
  # ListShelves methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true